// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrjApiLembrete.Context;

#nullable disable

namespace PrjApiLembrete.Migrations
{
    [DbContext(typeof(AppLembretesContext))]
    [Migration("20250311225451_CriaCaoTabelaLembrete")]
    partial class CriaCaoTabelaLembrete
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PrjApiLembrete.Entities.Lembrete", b =>
                {
                    b.Property<int>("LembreteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CorpoLembrete")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("StatusLembrete")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("TituloLembrete")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("LembreteId");

                    b.ToTable("Lembretes");
                });
#pragma warning restore 612, 618
        }
    }
}
